import type { StrategySummary } from './types';

/**
 * Hand-written sample strategies for the home listing — no DB yet (slice ordering:
 * fun before plumbing). Replaced by the data-access layer when persistence lands.
 */
export const sampleStrategies: StrategySummary[] = [
  {
    id: '1',
    slug: 'harvest-lifeforce-juicing',
    title: 'Harvest Lifeforce Juicing',
    author: 'Exileph',
    authorAvatar: null,
    league: 'Settlers',
    mechanic: 'harvest',
    mechanicTags: ['harvest'],
    tier: 'A',
    difficulty: 2,
    returnPerHour: 2.4,
    investPerMap: 12,
    scarabCount: 5,
    updatedDaysAgo: 2,
  },
  {
    id: '2',
    slug: 'breach-hands-rush',
    title: 'Breach Hands Splinter Rush',
    author: 'Mapaholic',
    authorAvatar: null,
    league: 'Settlers',
    mechanic: 'breach',
    mechanicTags: ['breach'],
    tier: 'S',
    difficulty: 3,
    returnPerHour: 3.1,
    investPerMap: 28,
    scarabCount: 4,
    updatedDaysAgo: 1,
  },
  {
    id: '3',
    slug: 'legion-generals-farm',
    title: "Legion Generals' Farm",
    author: 'Exileph',
    authorAvatar: null,
    league: 'Settlers',
    mechanic: 'legion',
    mechanicTags: ['legion'],
    tier: 'A',
    difficulty: 2,
    returnPerHour: 1.9,
    investPerMap: 14,
    scarabCount: 5,
    updatedDaysAgo: 5,
  },
  {
    id: '4',
    slug: 'essence-hunting-budget',
    title: 'Essence Hunting on a Budget',
    author: 'Slumlord',
    authorAvatar: null,
    league: 'Settlers',
    mechanic: 'essence',
    mechanicTags: ['essence'],
    tier: 'B',
    difficulty: 1,
    returnPerHour: 1.1,
    investPerMap: 4,
    scarabCount: 3,
    updatedDaysAgo: 3,
  },
  {
    id: '5',
    slug: 'expedition-logbook-runner',
    title: 'Expedition Logbook Runner',
    author: 'Digsy',
    authorAvatar: null,
    league: 'Standard',
    mechanic: 'expedition',
    mechanicTags: ['expedition'],
    tier: 'A',
    difficulty: 2,
    returnPerHour: 2.7,
    investPerMap: 18,
    scarabCount: 4,
    updatedDaysAgo: 9,
  },
  {
    id: '6',
    slug: 'ritual-reroll-engine',
    title: 'Ritual Reroll Engine',
    author: 'Mapaholic',
    authorAvatar: null,
    league: 'Settlers',
    mechanic: 'ritual',
    mechanicTags: ['ritual'],
    tier: 'B',
    difficulty: 3,
    returnPerHour: 2.0,
    investPerMap: 16,
    scarabCount: 5,
    updatedDaysAgo: 6,
  },
  {
    id: '7',
    slug: 'blight-oil-pipeline',
    title: 'Blight Oil Pipeline',
    author: 'Towerlord',
    authorAvatar: null,
    league: 'Settlers',
    mechanic: 'blight',
    mechanicTags: ['blight'],
    tier: 'A',
    difficulty: 2,
    returnPerHour: 2.2,
    investPerMap: 10,
    scarabCount: 4,
    updatedDaysAgo: 4,
  },
  {
    id: '8',
    slug: 'ambush-strongbox-loaded',
    title: 'Ambush Strongbox Loaded',
    author: 'Boxer',
    authorAvatar: null,
    league: 'Settlers',
    mechanic: 'ambush',
    mechanicTags: ['ambush'],
    tier: 'B',
    difficulty: 1,
    returnPerHour: 1.4,
    investPerMap: 7,
    scarabCount: 5,
    updatedDaysAgo: 8,
  },
  {
    id: '9',
    slug: 'delirium-mirror-rush',
    title: 'Delirium Mirror Rush',
    author: 'Foggy',
    authorAvatar: null,
    league: 'Settlers',
    mechanic: 'delirium',
    mechanicTags: ['delirium'],
    tier: 'S',
    difficulty: 3,
    returnPerHour: 3.4,
    investPerMap: 34,
    scarabCount: 5,
    updatedDaysAgo: 1,
  },
  {
    id: '10',
    slug: 'harvest-t17-juice',
    title: 'Harvest T17 Mega Juice',
    author: 'Exileph',
    authorAvatar: null,
    league: 'Settlers',
    mechanic: 'harvest',
    mechanicTags: ['harvest'],
    tier: 'S',
    difficulty: 3,
    returnPerHour: 4.0,
    investPerMap: 60,
    scarabCount: 5,
    updatedDaysAgo: 2,
  },
  {
    id: '11',
    slug: 'breach-standard-blast',
    title: 'Breach Standard Blast',
    author: 'Oldtimer',
    authorAvatar: null,
    league: 'Standard',
    mechanic: 'breach',
    mechanicTags: ['breach'],
    tier: 'B',
    difficulty: 2,
    returnPerHour: 1.7,
    investPerMap: 11,
    scarabCount: 3,
    updatedDaysAgo: 14,
  },
  {
    id: '12',
    slug: 'essence-scarab-stack',
    title: 'Essence Scarab Stack',
    author: 'Slumlord',
    authorAvatar: null,
    league: 'Settlers',
    mechanic: 'essence',
    mechanicTags: ['essence'],
    tier: 'A',
    difficulty: 2,
    returnPerHour: 2.1,
    investPerMap: 13,
    scarabCount: 5,
    updatedDaysAgo: 7,
  },
  {
    id: '13',
    slug: 'legion-emblem-farm',
    title: 'Legion Emblem Farm',
    author: 'Marshal',
    authorAvatar: null,
    league: 'Settlers',
    mechanic: 'legion',
    mechanicTags: ['legion'],
    tier: 'A',
    difficulty: 2,
    returnPerHour: 2.5,
    investPerMap: 20,
    scarabCount: 4,
    updatedDaysAgo: 10,
  },
  {
    id: '14',
    slug: 'expedition-rog-rotation',
    title: 'Expedition Rog Rotation',
    author: 'Digsy',
    authorAvatar: null,
    league: 'Settlers',
    mechanic: 'expedition',
    mechanicTags: ['expedition'],
    tier: 'B',
    difficulty: 1,
    returnPerHour: 1.3,
    investPerMap: 6,
    scarabCount: 3,
    updatedDaysAgo: 12,
  },
  {
    id: '15',
    slug: 'ritual-fragment-blueprint',
    title: 'Ritual Fragment Blueprint',
    author: 'Mapaholic',
    authorAvatar: null,
    league: 'Settlers',
    mechanic: 'ritual',
    mechanicTags: ['ritual'],
    tier: 'A',
    difficulty: 2,
    returnPerHour: 2.3,
    investPerMap: 15,
    scarabCount: 5,
    updatedDaysAgo: 3,
  },
];
