import type { StrategySummary } from './types';

/**
 * Hand-written sample strategies for the home listing — no DB yet (slice ordering:
 * fun before plumbing). Replaced by the data-access layer when persistence lands.
 */
export const sampleStrategies: StrategySummary[] = [
  {
    id: '1',
    slug: 'harvest-lifeforce-juicing',
    title: 'Harvest Lifeforce Juicing',
    author: 'Exileph',
    league: 'Settlers',
    mechanic: 'harvest',
    mechanicTags: ['harvest'],
    tier: 'A',
    difficulty: 2,
    returnPerHour: 2.4,
    investPerMap: 12,
    scarabCount: 5,
    updatedDaysAgo: 2,
  },
  {
    id: '2',
    slug: 'breach-hands-rush',
    title: 'Breach Hands Splinter Rush',
    author: 'Mapaholic',
    league: 'Settlers',
    mechanic: 'breach',
    mechanicTags: ['breach'],
    tier: 'S',
    difficulty: 3,
    returnPerHour: 3.1,
    investPerMap: 28,
    scarabCount: 4,
    updatedDaysAgo: 1,
  },
  {
    id: '3',
    slug: 'legion-generals-farm',
    title: "Legion Generals' Farm",
    author: 'Exileph',
    league: 'Settlers',
    mechanic: 'legion',
    mechanicTags: ['legion'],
    tier: 'A',
    difficulty: 2,
    returnPerHour: 1.9,
    investPerMap: 14,
    scarabCount: 5,
    updatedDaysAgo: 5,
  },
  {
    id: '4',
    slug: 'essence-hunting-budget',
    title: 'Essence Hunting on a Budget',
    author: 'Slumlord',
    league: 'Settlers',
    mechanic: 'essence',
    mechanicTags: ['essence'],
    tier: 'B',
    difficulty: 1,
    returnPerHour: 1.1,
    investPerMap: 4,
    scarabCount: 3,
    updatedDaysAgo: 3,
  },
  {
    id: '5',
    slug: 'expedition-logbook-runner',
    title: 'Expedition Logbook Runner',
    author: 'Digsy',
    league: 'Standard',
    mechanic: 'expedition',
    mechanicTags: ['expedition'],
    tier: 'A',
    difficulty: 2,
    returnPerHour: 2.7,
    investPerMap: 18,
    scarabCount: 4,
    updatedDaysAgo: 9,
  },
  {
    id: '6',
    slug: 'ritual-reroll-engine',
    title: 'Ritual Reroll Engine',
    author: 'Mapaholic',
    league: 'Settlers',
    mechanic: 'ritual',
    mechanicTags: ['ritual'],
    tier: 'B',
    difficulty: 3,
    returnPerHour: 2.0,
    investPerMap: 16,
    scarabCount: 5,
    updatedDaysAgo: 6,
  },
];
